### ISSUE TITLE
Scene saved validator

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-magenta#37]
Because UUIDs are written on scene-save, we'll need to be sure the scene actually has been saved before publishing.

**Comment by BigRoy** [comment]
This was included in one of the earlier commits.

The two relevant plug-ins at the time were:
https://github.com/pyblish/pyblish-magenta/blob/ba658c67cc4b6cc684f98db89bfba4b54699f3aa/pyblish_magenta/plugins/_validate_scene_saved.py
https://github.com/pyblish/pyblish-magenta/blob/ba658c67cc4b6cc684f98db89bfba4b54699f3aa/pyblish_magenta/plugins/collect_scene_modified.py

Note that I disabled it back then because it was annoying that some of the Collectors or method calls would make Maya assume the scene was modified even if only queried for content. For example, does `cmds.file(exportSelected=True, preview=True)` trigger a _scene modified_? There are likely many commands that trigger it.

We should look into how it's made comfortable for the artist. Because from time to time I pressed _save_ and then tried to publish directly and it got invalidated because the scene was supposedly modified.

**Comment by mottosso** [comment]
Mm, I remember, also experienced this.

Something to look out for. Perhaps it's ok to ensure it has been saved at least once. Though it would mean missing out on potentially new nodes leaving without a UUID.

Another alternative could be to add another callback to scene saved, imprint the time at which is was saved. The validator could then take this into account.

Not very clean, just throwing it out as an option.

**Comment by BigRoy** [comment]
I think we're tackling the issue the wrong way. 

Shouldn't the validator just validate that all nodes included in the extraction have a UUID? And in modeling also ensure they are unique? (Two separate validators I assume)

**Comment by mottosso** [comment]
Good thinking!

**Comment by BigRoy** [comment]
Shall we close this since we covered this particular problem from that time with a lot of different solutions?
